project:
  type: website
  output-dir: _site

website:
  title: "Essha Khan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: Resume_EsshaKhan.pdf
        text: Resume
      - href: contact.qmd
        text: Contact


format:
  html:
    theme: journal
    toc: true
