project:
  type: website
  output-dir: _site

website:
  title: "Essha Khan"
  navbar: false
  favicon: assets/favicon.svg

format:
  html:
    theme: none
    css: styles.css
    toc: false
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap

    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    include-after-body:
      - text: |
          <script src="/scripts.js"></script>

execute:
  freeze: auto