project:
  type: website
  output-dir: _site

website:
  title: "Essha Khan"
  navbar:
    left:
      - text: Home
        href: index.qmd

      - text: About
        href: about.qmd

      - text: Projects
        menu:
          - text: Food Delivery Platform
            href: fooddeliveryplatform.qmd
          - text: Airbnb Presentation
            href: airbnbproject.qmd

      - text: Resume
        href: Resume_EsshaKhan.pdf

      - text: Contact
        href: contact.qmd

format:
  html:
    theme: journal
    toc: true